services:
  - type: web
    name: shop-meeting-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 wsgi:app
    rootDir: server
